"""add assessment state

Revision ID: 067ccc1b79a6
Revises: 799b6623b602
Create Date: 2026-09-16 22:21:03.432602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067ccc1b79a6'
down_revision: Union[str, Sequence[str], None] = '799b6623b602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_question', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['learning_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_sessions_program_id'), ['program_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=150), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('learner_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'sequence_number', name='uq_assessment_question_sequence')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_questions_assessment_id'))

    op.drop_table('assessment_questions')
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_program_id'))

    op.drop_table('assessment_sessions')
    # ### end Alembic commands ###
