"""add knowledge pages

Revision ID: 075812189788
Revises: df931e350532
Create Date: 2026-09-17 14:09:00.995946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075812189788'
down_revision: Union[str, Sequence[str], None] = 'df931e350532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('has_text', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'page_number', name='uq_knowledge_source_page')
    )
    with op.batch_alter_table('knowledge_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_pages_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_pages_source_id'))

    op.drop_table('knowledge_pages')
    # ### end Alembic commands ###
