"""add learning programs

Revision ID: 799b6623b602
Revises: f4ca07a0b4a7
Create Date: 2026-09-16 21:15:02.959738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799b6623b602'
down_revision: Union[str, Sequence[str], None] = 'f4ca07a0b4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('starting_strategy', sa.String(length=30), nullable=False),
    sa.Column('selected_level', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('curriculum_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_type', name='uq_user_program_type')
    )
    with op.batch_alter_table('learning_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_programs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_programs_user_id'))

    op.drop_table('learning_programs')
    # ### end Alembic commands ###
