"""add assessment question metadata

Revision ID: ca5318ba0401
Revises: 067ccc1b79a6
Create Date: 2026-09-16 22:29:35.027895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5318ba0401'
down_revision: Union[str, Sequence[str], None] = '067ccc1b79a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_topics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evaluator_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_column('evaluator_notes')
        batch_op.drop_column('expected_topics')

    # ### end Alembic commands ###
